import { existsSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

/* blog/<slug>.html permalink entries, generated by the npm prebuild
   script (scripts/gen-blog-pages.mjs) from src/content/blog.ts */
const blogDir = resolve(__dirname, 'blog')
const blogPages = existsSync(blogDir)
  ? Object.fromEntries(
      readdirSync(blogDir)
        .filter((f) => f.endsWith('.html'))
        .map((f) => [`blog-${f.replace(/\.html$/, '')}`, resolve(blogDir, f)]),
    )
  : {}

export default defineConfig({
  /* relative base so the build works at a domain root, a GitHub Pages
     subpath, or any static host without changes */
  base: './',
  plugins: [react(), tailwindcss()],
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        about: resolve(__dirname, 'about.html'),
        video: resolve(__dirname, 'video.html'),
        press: resolve(__dirname, 'press.html'),
        blog: resolve(__dirname, 'blog.html'),
        contact: resolve(__dirname, 'contact.html'),
        ...blogPages,
      },
    },
  },
})
